# Generated by Django 3.2.4 on 2023-01-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_user_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('n/a', 'N/A'), ('casual_leave', 'Casual Leave'), ('sick_leave', 'Sick Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'Paternity Leave'), ('loss_of_pay_leave', 'Loss of Pay Leave'), ('emergency', 'Emergency Leave')], default='N/A', max_length=50, verbose_name='Leave Type')),
                ('leave_balance', models.IntegerField(default=0, verbose_name='Leave Balance')),
                ('from_date', models.DateTimeField(verbose_name='From Date')),
                ('to_date', models.DateTimeField(verbose_name='To Date')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('description', models.CharField(db_index=True, default='Description & Responsibilities Assigned', max_length=400, verbose_name='Notes')),
                ('leave_status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='applied', max_length=30, null=True, verbose_name='Leave Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='users.user')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
    ]
